# -*- coding: utf-8 -*-
"""SMS Text Class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqakoBUx6_oNglpaoXcUZDM0vbCe8RK7

*Note: You are currently reading this using Google Colaboratory which is a cloud-hosted version of Jupyter Notebook. This is a document containing both text cells for documentation and runnable code cells. If you are unfamiliar with Jupyter Notebook, watch this 3-minute introduction before starting this challenge: https://www.youtube.com/watch?v=inN8seMm7UI*

---

In this challenge, you need to create a machine learning model that will classify SMS messages as either "ham" or "spam". A "ham" message is a normal message sent by a friend. A "spam" message is an advertisement or a message sent by a company.

You should create a function called `predict_message` that takes a message string as an argument and returns a list. The first element in the list should be a number between zero and one that indicates the likeliness of "ham" (0) or "spam" (1). The second element in the list should be the word "ham" or "spam", depending on which is most likely.

For this challenge, you will use the [SMS Spam Collection dataset](http://www.dt.fee.unicamp.br/~tiago/smsspamcollection/). The dataset has already been grouped into train data and test data.

The first two cells import the libraries and data. The final cell tests your model and function. Add your code in between these cells.
"""

# import libraries
try:
  # %tensorflow_version only exists in Colab.
  !pip install tf-nightly
except Exception:
  pass
import tensorflow as tf
import pandas as pd
from tensorflow import keras
!pip install tensorflow-datasets
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers

print(tf.__version__)

# get data files
!wget https://cdn.freecodecamp.org/project-data/sms/train-data.tsv
!wget https://cdn.freecodecamp.org/project-data/sms/valid-data.tsv

train_file_path = "train-data.tsv"
test_file_path = "valid-data.tsv"

#Load data into pandas dataframes
train = pd.read_csv(train_file_path, sep ='\t',names=["label", "message"])
test = pd.read_csv(test_file_path, sep ='\t',names=["label", "message"])

train[:3]

train.describe()

import seaborn as sns

#There is an inbalance in the data, fix it for training with downsampling
ham_msg = train[train.label =='ham']
spam_msg = train[train.label=='spam']
plt.figure(figsize=(8,6))
sns.countplot(train.label)
(len(spam_msg)/len(ham_msg))*100

#Downsampling the ham msg's
ham_msg_df = ham_msg.sample(n = len(spam_msg), random_state = 44)
spam_msg_df = spam_msg
print(ham_msg_df.shape, spam_msg_df.shape)

train_msg = ham_msg_df.append(spam_msg_df).reset_index(drop=True)

# Map ham label as 0 and spam as 1
train_msg['msg_type']= train_msg['label'].map({'ham': 0, 'spam': 1})
train_label = train_msg['msg_type'].values

test['msg_type']= test['label'].map({'ham': 0, 'spam': 1})
test_labels = test['msg_type'].values

print(train_msg)

# Defining pre-processing hyperparameters
max_len = 50 
trunc_type = "post" 
padding_type = "post" 
oov_tok = "<OOV>" 
vocab_size = 500

from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words = vocab_size, char_level=False, oov_token = oov_tok)
tokenizer.fit_on_texts(train_msg['message'])

word_index = tokenizer.word_index
word_index

# Sequencing and padding on training and testing 
training_sequences = tokenizer.texts_to_sequences(train_msg['message'])
training_padded = keras.preprocessing.sequence.pad_sequences (training_sequences, maxlen = max_len, 
                                 padding = padding_type, truncating = trunc_type )

testing_sequences = tokenizer.texts_to_sequences(test['message'])
testing_padded = keras.preprocessing.sequence.pad_sequences(testing_sequences, maxlen = max_len,
                              padding = padding_type, truncating = trunc_type)

print(training_padded[0])

#LSTM layer arcitecture hyperparameters
n_lstm = 20
drop_lstm =0.2
embeding_dim = 16

#LSTM model
model1 = keras.Sequential()
model1.add(keras.layers.Embedding(vocab_size, embeding_dim, input_length=max_len))
model1.add(keras.layers.LSTM(n_lstm, dropout=drop_lstm, return_sequences=True))
model1.add(keras.layers.LSTM(n_lstm, dropout=drop_lstm, return_sequences=True))
model1.add(keras.layers.Dense(1, activation='sigmoid'))

#Compile and train the model
model1.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])
# Training
num_epochs = 30
history = model1.fit(training_padded, train_label, epochs=num_epochs, 
                    verbose=2)

model.save('LSTM.h5')

# Run this cell to test your function and model. Do not modify contents.
def test_predictions():
  test_messages = ["how are you doing today",
                   "sale today! to stop texts call 98912460324",
                   "i dont want to go. can we try it a different day? available sat",
                   "our new mobile video service is live. just install on your phone to start watching.",
                   "you have won £1000 cash! call to claim your prize.",
                   "i'll bring it tomorrow. don't forget the milk.",
                   "wow, is your arm alright. that happened to me one time too"
                  ]

  test_answers = ["ham", "spam", "ham", "spam", "spam", "ham", "ham"]
  passed = True

  for msg, ans in zip(test_messages, test_answers):
    prediction = predict_message(msg)
    if prediction[1] != ans:
      passed = False

  if passed:
    print("You passed the challenge. Great job!")
  else:
    print("You haven't passed yet. Keep trying.")

test_predictions()